#!/opt/pwn.college/bash

if [ -t 1 ] || [ -f /dev/fd/1 ]
then
	fold -s >&2 <<< "你必须将我的输出重定向到另一个命令中！"
	exit 1
fi

fold -s <<< "这些机密数据必须直接且同时地送达 /challenge/the 和 /challenge/planet。不要试图复制粘贴它；它变化得太快了。"
cat /challenge/.challenge-key
