#!/opt/pwn.college/bash

if [ "$#" -eq 0 ]
then
	fold -s <<< "用法不正确!你必须给我传递一个参数(详情请阅读挑战描述)."
	exit 1
fi

if [ "$1" != "--printfile" ]
then
	fold -s <<< "用法不正确!你传递了错误的参数(详情请阅读挑战描述)."
	exit 2
fi

if [ "$#" -eq 1 ]
then
	fold -s <<< "你必须为 --printfile 传递一个要读取的文件!"
	exit 3
fi

echo "参数正确!这是 $2 文件的内容: "
cat "$2"
