#!/opt/pwn.college/bash

/bin/fold -s <<< "正在尝试移除 /flag..."
rm -f /flag

if [ -f /flag ]
then
	/bin/fold -s <<< "flag 还在！我不如就把它给你吧！"
	/bin/cat /flag
else
	/bin/fold -s <<< "哦哦，看来我成功移除了 flag！这意味着你没有正确设置 PATH 来阻止我找到 'rm'。既然 flag 已经没了，你需要从模块页面重新启动挑战！下次好运。"
fi
