#!/bin/bash

if ls -l /proc/$$/fd/{0,1,2} | grep -vq pts
then
	echo -e "看起来你可能使用了管道或其他输入重定向方法来链接此命令。\n在本关卡中，你必须将这些命令写成脚本，让它们一个接一个地运行，而不要使用管道或重定向！" 1>&2
	exit
fi

if [ "$1" == ";" ]
then
	echo "看起来你把分号放在了引号里，这会导致 shell 对它进行不同的处理。"
	echo "请直接使用原始的分号（;）！"
	exit
fi

touch /tmp/.pwn
