#!/opt/pwn.college/bash

if [ ! -t 1 ]
then
	echo "错误！" 1>&2
	printf '看起来你正在重定向我的标准输出！这不是你用来保存退出码的方式。\n退出码不会被输出到任何地方；它只是作为这个程序退出时的返回值。\n它最终会存放在 $? 变量中。\n请在不使用输出重定向的情况下重新运行此程序。\n' >&2
	exit 1
fi

CODE=$(($RANDOM%255+1))
echo "正在以一个退出码退出！"
echo "$CODE" > /tmp/.code
exit "$CODE"
