#!/opt/pwn.college/bash

read -a ARGS < /tmp/.last_arg

if [ "$PWD" != "/challenge/files" ]
then
	fold -s <<< "错误：请在 /challenge/files 工作目录下运行本程序！"
	exit 1
fi

if [ "${#ARGS[@]}" -eq 0 ]
then
	fold -s <<< "错误：你运行此命令时未提供任何参数！请提供一个参数来运行我。"
	exit 2
fi

if [ "${#ARGS[@]}" -gt 1 ]
then
	fold -s <<< "错误:你运行此命令时提供了超过1个参数(在通配符扩展前)!请提供一个参数来运行我."
	exit 3
fi

if [[ "${ARGS[0]}" != *"["* ]]
then
	fold -s <<< "错误：你没有使用方括号通配符..."
	exit 4
fi

if [ "$1" == "file_a" ] && [ "$2" == "file_b" ] && [ "$3" == "file_h" ] && [ "$4" == "file_s" ]
then
	fold -s <<< "你做对了！这是你的flag!"
	cat /flag
else
	fold -s <<< "你的通配符没有扩展为所要求的文件（file_a、file_b、file_h 和 file_s）。它实际扩展为了："
	echo "$@"
fi
